name = "TensorTrainApprox"
uuid = "1940a7fa-26bb-40ed-82aa-2c0b66cfb046"
authors = ["Richard Dennis <richard.dennis@glasgow.ac.uk>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
