name = "TensorTrainApprox"
uuid = "1940a7fa-26bb-40ed-82aa-2c0b66cfb046"
authors = ["Richard Dennis <richard.dennis@glasgow.ac.uk>"]
version = "0.2.0"

[deps]
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Maxvol = "4cc553b9-be87-484b-81d9-b5ae2a4e3958"

[compat]
GaussQuadrature = "^0.5"
Maxvol = "^1.0"
GenericLinearAlgebra = "^0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
